In [5]:
import pandas as pd
import datetime
from random import randrange

In [6]:
def random_time(start,i):
    """ This function for creatting random attendence time for people as a test data.

    Args:
        start: datatime object.
        i: number of random times we want to create each time.
    """
    current = start
    while i >= 0:
        curr = current + datetime.timedelta(hours=randrange(8,11),minutes=randrange(59),seconds=randrange(59))
        yield curr
        i -=1

In [7]:
##### Reading the file as a pandas DataFrame #####
dataset = pd.read_csv('D:/Attendency Project/Attendence.csv')

##### Creating datetime object #####
time = datetime.datetime(2022,5,8,0,0,0)

##### Getting the date of today in a specific format #####
today = datetime.datetime.strptime(datetime.datetime.today().strftime('%d-%B-%Y'),'%d-%B-%Y')

##### Creating ranomd data using random_time() function and today's date #####
for i,j in zip(range(-202,0),range(0,202)):
    dataset.loc[j] = [x.strftime('%H:%M:%S') for x,y in zip(random_time(time,5),range(len(dataset.columns)))]
    x = today + datetime.timedelta(days=i)
    dataset.at[j,'Day'] = x.strftime('%d-%B-%Y')

##### Creating random absence days for people #####
i = 40
while i > 0:
    x = randrange(202)
    dataset.at[x,'Elon Mask'] = "Absent"
    i -= 1

i = 50
while i > 0:
    x = randrange(202)
    dataset.at[x,'Ahmed Zewail'] = "Absent"
    i -= 1

i = 55
while i > 0:
    x = randrange(202)
    dataset.at[x,'Jeff Bezos'] = "Absent"
    i -= 1



dataset.to_csv('D:/Attendency Project/Attendence.csv',index=False)

In [8]:
data = pd.read_csv("D:/Attendency Project/Attendence.csv")
data

                  Day Elon Mask Ahmed Zewail Jeff Bezos
0    01-November-2021  10:55:35     10:16:17   10:18:24
1    02-November-2021  10:38:53     10:58:01     Absent
2    03-November-2021  10:04:41     08:42:47   08:45:58
3    04-November-2021  09:19:46     10:20:48   09:22:12
4    05-November-2021  10:16:02     09:18:09   10:11:18
..                ...       ...          ...        ...
199       19-May-2022  10:10:05       Absent     Absent
200       20-May-2022  10:05:30       Absent   10:50:10
201       21-May-2022  08:28:22     10:20:53   08:52:21
202       21-May-2022  08:29:32     08:23:33   08:20:13
203       22-May-2022  00:49:46     00:50:02   00:49:58

[204 rows x 4 columns]